#ifndef __DEFAULT_APP_CONFIG_H__
#define __DEFAULT_APP_CONFIG_H__

#include <ESP8266WiFi.h>

#define DEFAULT_WIFI_SSID "WifiSocketII-%06x"
#define DEFAULT_WIFI_PASSWORD "12345678"
#define DEFAULT_WIFI_MODE WIFI_AP

#define DEFAULT_NET_MODE NET_MODE_DHCP
#define DEFAULT_NET_HOST "192.168.192.1"
#define DEFAULT_NET_MASK "255.255.255.0"
#define DEFAULT_NET_GATEWAY "192.168.192.1"
#define DEFAULT_NET_DNS "192.168.192.1"

#define DEFAULT_OTA_HOSTNAME "wifi-socket-1"
#define DEFAULT_OTA_PASSWORD "otapass"

#define DEFAULT_ADMIN_PASSWORD "admin"

#define DEFAULT_OHAB_ENABLED false
#define DEFAULT_OHAB_VERSION 1
#define DEFAULT_OHAB_HOST "192.168.1.1"
#define DEFAULT_OHAB_PORT 80
#define DEFAULT_OHAB_USEAUTH true
#define DEFAULT_OHAB_USER "user"
#define DEFAULT_OHAB_PASSWORD "password"
#define DEFAULT_OHAB_ITEMNAME "WifiSocket1"
#define DEFAULT_OHAB_ITEM_VOLTAGE "WifiSocket1Voltage"
#define DEFAULT_OHAB_ITEM_CURRENT "WifiSocket1Current"
#define DEFAULT_OHAB_ITEM_POWER "WifiSocket1Power"
#define DEFAULT_OHAB_SENDING_INTERVAL 60

#define DEFAULT_ALEXA_ENABLED false
#define DEFAULT_ALEXA_DEVICENAME "Socket"

#define DEFAULT_MQTT_ENABLED false
#define DEFAULT_MQTT_CLIENTID "WifiSocket1"
#define DEFAULT_MQTT_HOST "192.168.1.1"
#define DEFAULT_MQTT_PORT 1883
#define DEFAULT_MQTT_USEAUTH true
#define DEFAULT_MQTT_USER "user"
#define DEFAULT_MQTT_PASSWORD "password"
#define DEFAULT_MQTT_INTOPIC "socket1/in"
#define DEFAULT_MQTT_OUTTOPIC "socket1/out"
#define DEFAULT_MQTT_TOPIC_VOLTAGE "socket1/voltage"
#define DEFAULT_MQTT_TOPIC_CURRENT "socket1/current"
#define DEFAULT_MQTT_TOPIC_POWER "socket1/power"
#define DEFAULT_MQTT_TOPIC_JSON "socket1/json"
#define DEFAULT_MQTT_SENDING_INTERVAL 60

#define DEFAULT_SYSLOG_ENABLED false
#define DEFAULT_SYSLOG_HOST "192.168.1.1"
#define DEFAULT_SYSLOG_PORT 514
#define DEFAULT_SYSLOG_APP_NAME "wifi-socket"

#define DEFAULT_POWER_BUTTON_MODE POWER_BUTTON_MODE_TOGGLE_SWITCH

#define DEFAULT_LED_NIGHT_MODE_ENABLED false
#define DEFAULT_LED_NIGHT_MODE_TIMEOUT 15

#define DEFAULT_INET_CHECK_ENABLED false
#define DEFAULT_INET_CHECK_PERIOD 600
#define DEFAULT_INET_CHECK_ACTION INET_CHECK_ACTION_ON_DISCONNECT_SWITCH_OFF

#endif
